// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'splash', uri: Uri.parse('splash'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'user/user_details',
    uri: Uri.parse('user/user_details'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(key: 'user', uri: Uri.parse('user'), routeBuilder: b2Builder),
  RouteEntity(
    key: 'user/user_saved',
    uri: Uri.parse('user/user_saved'),
    routeBuilder: b3Builder,
  ),
];

const routePaths = (
  path: '/',
  splash: '/splash',
  user: (
    path: '/user',
    userDetails: '/user/user_details',
    userSaved: '/user/user_saved',
  ),
);
