// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:bus_teste/domain/entities/user_entity.dart';
import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'ui/home_page.dart' as a1;
import 'ui/splash/splash_page.dart' as a0;
import 'ui/user/user_details_page.dart' as a2;
import 'ui/user/user_saved_page.dart' as a3;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a0.SplashPage());
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a1.HomePage());
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      a2.UserDetailsPage(user: settings.arguments as UserEntity),
    );
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(ctx, settings, const a3.UserSavedPage());
